# -*- coding: utf-8 -*-
"""Calculadora | Atividade 1.14 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1esPN_XzzH90DXvRpzrtMeNARIFQYUFl_
"""

import time
from os import wait
from time import sleep
print('Esta é a sua nova calculadora! \nPor favor, digite o primeiro número para formar suas operações:\n')
Fator1 = int(input())
print("Você digitou o número",Fator1,",","correto?\n")
print("Agora, digite o símbolo da sua operação matemática desejada. As opções são:")
print("+ para adição \n- para subtração \n* para multiplicação \n/ para divisão \n")
Opera1 = str(input())
while Opera1 not in ("+","-","*","/"):
  print("Você não digitou o símbolo correto da operação matemática!")
  print("Tente novamente:\n+ para adição \n- para subtração \n* para multiplicação \n/ para divisão \n")
  Opera1 = str(input())

if Opera1 in ("+","-","*","/"):
  print("Você digitou o símbolo correto da operação matemática!")
  print("Agora, digite o segundo número para formar suas operações:\n")

Fator2 = int(input())
print("Você digitou o número",Fator2,",","correto?\n")
time.sleep(2)
print("Calculando ",Fator1,Opera1,Fator2,"...\n")
time.sleep(2)
if Opera1 == "+":
  print("O resultado é",Fator1+Fator2)
if Opera1 == "-":
  print("O resultado é",Fator1-Fator2)
if Opera1 == "*":
  print("O resultado é",Fator1*Fator2)
if Opera1 == "/":
  print("O resultado é",Fator1/Fator2)

print("Obrigado(a) por usar a calculadora!")